version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_container
    environment:
      POSTGRES_DB: airbnb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: CQaf7GWP85FJsogu
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: